選択肢の数に合わせたボタン表示
gary199887/TaisenGame pull request #23
Opened 2023-07-21 10:16 UTC by 0223sango

選択肢の数と同じ数だけボタンが表示されるように変更。
ボタンの数によってボタンの配置も変わるようにした。

### 主な変更点
 **AnswerSystemManager.cs**
1. **SetQATextメソッド** の中身を大幅改修。
2. ボタンの配置設定を行う **SetAnsButtonPosメソッド** の追加。

2023-07-23 02:28 UTC, gary199887 requested changes
ステージ番号に対応した問題文やボタン数設定は一面のものに固定されています。
コメント化されたステージ番号設定コードを実行したらちゃんと動くことを確認できましたので、当該コードのコメント化解除をお願いします。
他は動作的に特に問題ないです。

2023-07-23 02:28 UTC, gary199887 commented on Assets/Scripts/GameScene/AnswerSystem/AnswerSystemManager.cs
>          //stageNum = GameDirector.stage - 1;    // �X�e�[�W�ԍ����擾
今の挙動はこの一行がコメント化されたのが原因で二面でも一面の問題文が表示されています。

この行を実行したらステージごとの問題文になると確認しましたので、
非コメント化をお願いします。👏

2023-07-23 03:13 UTC, gary199887 approved these changes

2023-07-23 03:19 UTC, gary199887 commented
- 本PRの主な目標はあくまで”**選択肢数に応じてのボタン数や配置変更**”であって、
 ステージに対応する反映ではない。

- 本PRの目標自体は問題なく動作することを確認できましたため、masterにマージします。

- ステージごとの問題文の反映はまた別のPRでの対応をお願いします。

2023-07-23 03:19 UTC, merged

2023-07-24 09:22 UTC, 0223sango commented
> @0223sango
> 
> * 本PRの主な目標はあくまで”**選択肢数に応じてのボタン数や配置変更**”であって、
>   ステージに対応する反映ではない。
> * 本PRの目標自体は問題なく動作することを確認できましたため、masterにマージしました。
> * ステージごとの問題文反映はまた別のPRでの対応をお願いします。

了解しました。